"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
import PluginBuilderBase

# Implementing MainFrame
class Plugin BuilderMainFrame( PluginBuilderBase.MainFrame ):
	def __init__( self, parent ):
		PluginBuilderBase.MainFrame.__init__( self, parent )

